USE [master]
GO

/****** Object:  Database [FoodZone]    Script Date: 01/14/2014 13:46:59 ******/
CREATE DATABASE [FoodZone]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodZone', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\FoodZone.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FoodZone_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\FoodZone_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FoodZone] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodZone].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FoodZone] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FoodZone] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FoodZone] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FoodZone] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FoodZone] SET ARITHABORT OFF 
GO

ALTER DATABASE [FoodZone] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FoodZone] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FoodZone] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FoodZone] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FoodZone] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FoodZone] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FoodZone] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FoodZone] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FoodZone] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FoodZone] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FoodZone] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FoodZone] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FoodZone] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FoodZone] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FoodZone] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FoodZone] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FoodZone] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FoodZone] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FoodZone] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FoodZone] SET  MULTI_USER 
GO

ALTER DATABASE [FoodZone] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FoodZone] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FoodZone] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FoodZone] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FoodZone] SET  READ_WRITE 
GO

