//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodZone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodZoneEntities : DbContext
    {
        public FoodZoneEntities()
            : base("name=FoodZoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<HorarioPlato> HorarioPlatoes { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<Plato> Platoes { get; set; }
        public virtual DbSet<TipoLocal> TipoLocals { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuarios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
    }
}
