//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioPlato
    {
        public int Horari_Codigo { get; set; }
        public int Plato_Codigo { get; set; }
        public bool HorPla_Activo { get; set; }
        public string Usuari_Codigo { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Plato Plato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
