//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.HorarioPlatoes = new HashSet<HorarioPlato>();
        }
    
        public int Horari_Codigo { get; set; }
        public System.DateTime Horari_Fecha { get; set; }
        public System.TimeSpan Horari_HoraDesde { get; set; }
        public System.TimeSpan Horari_HoraHasta { get; set; }
        public int Horari_Grupo { get; set; }
        public string Local_Codigo { get; set; }
        public string Usuari_Codigo { get; set; }
    
        public virtual Local Local { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<HorarioPlato> HorarioPlatoes { get; set; }
    }
}
