//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoLocal
    {
        public TipoLocal()
        {
            this.Locals = new HashSet<Local>();
        }
    
        public string TipoLocal_Codigo { get; set; }
        public string TipoLocal_Descripcion { get; set; }
        public bool TipoLocal_Activo { get; set; }
    
        public virtual ICollection<Local> Locals { get; set; }
    }
}
