//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Horarios = new HashSet<Horario>();
            this.HorarioPlatoes = new HashSet<HorarioPlato>();
            this.Locals = new HashSet<Local>();
            this.Platoes = new HashSet<Plato>();
            this.Usuario1 = new HashSet<Usuario>();
        }
    
        public string Usuari_Codigo { get; set; }
        public string Usuari_NombreCompleto { get; set; }
        public string Usuari_Clave { get; set; }
        public string Usuari_Email { get; set; }
        public System.DateTime Usuari_FechaIngreso { get; set; }
        public string Usuari_UsuarioIngreso { get; set; }
        public bool Usuari_Activo { get; set; }
        public int TipoUsuario_Codigo { get; set; }
    
        public virtual ICollection<Horario> Horarios { get; set; }
        public virtual ICollection<HorarioPlato> HorarioPlatoes { get; set; }
        public virtual ICollection<Local> Locals { get; set; }
        public virtual ICollection<Plato> Platoes { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
    }
}
