//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        public Zona()
        {
            this.Locals = new HashSet<Local>();
        }
    
        public string Zona_Codigo { get; set; }
        public string Zona_Descripcion { get; set; }
        public float Zona_Longitud { get; set; }
        public float Zona_Latitud { get; set; }
        public bool Zona_Acitvo { get; set; }
    
        public virtual ICollection<Local> Locals { get; set; }
    }
}
